name: Test Hello HelloGHA
on:
  push:
    branches:
      - master
jobs:
  firstJob : 
    runs-on : ubuntu-latest
    steps:
      - name: "prints this is first job"
        env:
          super_secret: ${{secrets.FAVSPORT}} # setting super_secret as env variable
        run: |
            echo "this is first job"
            echo ${{github.actor}}
            echo "my fav color ${super_secret}"
            echo ${{secrets.FAVCOLER}}
            echo " mysecret1 : ${secrets.MYSECRET}"
            echo "fav color1 : ${secrets.MYSECRET.FAVCOLER}"
            echo "fav color2 : ${secrets.MYSECRET}.FAVCOLER"
            echo "fav color3 : ${{secrets.MYSECRET.FAVCOLER}}"
            echo "fav color4 : ${{secrets.MYSECRET}}.FAVCOLER"

  secondJob : 
    runs-on : windows-latest
    needs : ["firstJob"]
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name : "prints I depend on firstJob"
        run: |
          echo "I depend on firstJob"
          echo "This also checked out repo"


      
